import os
import json
import sqlite3
import pandas as pd
import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
from dotenv import load_dotenv

from db import get_connection, init_db
from embeddings import search_similar, get_chroma_client, embedder
from agents import run_agent_pipeline_on_circular

load_dotenv()

# Page configuration
st.set_page_config(
    page_title="AI Compliance Copilot | Bank of India",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for UI aesthetics
st.markdown("""
<style>
    .main-header {
        font-size: 2.2rem;
        font-weight: 700;
        color: #1E3A8A;
        margin-bottom: 0px;
    }
    .sub-header {
        font-size: 1.0rem;
        color: #4B5563;
        margin-bottom: 20px;
    }
    .metric-card {
        background-color: #F8FAFC;
        border-radius: 10px;
        padding: 15px;
        border-left: 5px solid #3B82F6;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .badge-high {
        background-color: #FEE2E2;
        color: #991B1B;
        padding: 4px 10px;
        border-radius: 12px;
        font-weight: 600;
        font-size: 0.85rem;
    }
    .badge-medium {
        background-color: #FEF3C7;
        color: #92400E;
        padding: 4px 10px;
        border-radius: 12px;
        font-weight: 600;
        font-size: 0.85rem;
    }
    .badge-low {
        background-color: #E0E7FF;
        color: #3730A3;
        padding: 4px 10px;
        border-radius: 12px;
        font-weight: 600;
        font-size: 0.85rem;
    }
</style>
""", unsafe_allow_html=True)

init_db()

# Sidebar Navigation
st.sidebar.image("https://img.icons8.com/color/96/shield-with-signature.png", width=70)
st.sidebar.title("Compliance Copilot")
st.sidebar.caption("Indian BFSI Regulatory Drift System")

nav_view = st.sidebar.radio(
    "Navigation",
    ["🎟️ Compliance Tickets", "📊 Drift Score Analytics", "📜 RBI Audit Trail", "💬 Ask AI (RAG Chatbot)"]
)

st.sidebar.markdown("---")
st.sidebar.subheader("System Status")
st.sidebar.success("● Database: Connected (SQLite)")
st.sidebar.info("● Vector Store: Active (ChromaDB)")
st.sidebar.info("● Ollama LLM: Qwen 2.5 14B")

# Helper Data Functions
def fetch_tickets():
    conn = get_connection()
    df = pd.read_sql_query("SELECT * FROM compliance_tickets ORDER BY created_at DESC", conn)
    conn.close()
    return df

def fetch_audit_logs():
    conn = get_connection()
    df = pd.read_sql_query("SELECT * FROM compliance_audit ORDER BY id DESC", conn)
    conn.close()
    return df

def fetch_queue():
    conn = get_connection()
    df = pd.read_sql_query("SELECT * FROM document_queue ORDER BY id DESC", conn)
    conn.close()
    return df

# ---------------------------------------------------------
# VIEW 1: TICKETS
# ---------------------------------------------------------
if nav_view == "🎟️ Compliance Tickets":
    st.markdown('<div class="main-header">Compliance Tickets</div>', unsafe_allow_html=True)
    st.markdown('<div class="sub-header">Actionable compliance tickets generated by 3-agent LangGraph workflow</div>', unsafe_allow_html=True)

    df_tickets = fetch_tickets()

    if df_tickets.empty:
        st.warning("No compliance tickets found in SQLite database. Run `python run_pipeline.py` to process queued circulars.")
    else:
        # Metrics Top Bar
        col1, col2, col3, col4 = st.columns(4)
        high_count = len(df_tickets[df_tickets["priority"].str.contains("HIGH", na=False)])
        med_count = len(df_tickets[df_tickets["priority"].str.contains("MEDIUM", na=False)])
        low_count = len(df_tickets[df_tickets["priority"].str.contains("LOW", na=False)])

        with col1:
            st.metric("Total Tickets", len(df_tickets))
        with col2:
            st.metric("High Priority (P1)", high_count)
        with col3:
            st.metric("Medium Priority (P2)", med_count)
        with col4:
            st.metric("Low Priority (P3)", low_count)

        st.markdown("---")
        
        # Filter controls
        reg_filter = st.multiselect("Filter by Regulator", options=df_tickets["regulator"].unique(), default=df_tickets["regulator"].unique())
        prio_filter = st.multiselect("Filter by Priority", options=df_tickets["priority"].unique(), default=df_tickets["priority"].unique())

        filtered_df = df_tickets[
            (df_tickets["regulator"].isin(reg_filter)) &
            (df_tickets["priority"].isin(prio_filter))
        ]

        for idx, row in filtered_df.iterrows():
            priority_str = row["priority"]
            badge_class = "badge-high" if "HIGH" in priority_str else ("badge-medium" if "MEDIUM" in priority_str else "badge-low")
            
            with st.expander(f"📌 [{row['ticket_id']}] {row['regulator']} - {row['domain']} (Drift Score: {row['drift_score']:.2f})", expanded=(idx==0)):
                st.markdown(f"**Priority**: <span class='{badge_class}'>{priority_str}</span> | **Regulator**: `{row['regulator']}` | **Domain**: `{row['domain']}` | **Status**: `{row['status']}`", unsafe_allow_html=True)
                st.markdown(f"**Circular ID**: `{row['circular_id']}` | **Created At**: `{row['created_at']}`")
                
                st.markdown("### Executive Summary")
                st.info(row["summary"])

                st.markdown("### Affected Internal Policies")
                try:
                    policies = json.loads(row["affected_policies"])
                    for p in policies:
                        st.markdown(f"- 📄 **{p}**")
                except Exception:
                    st.write(row["affected_policies"])

                st.markdown("### Actionable Change Items")
                try:
                    changes = json.loads(row["change_list"])
                    for c in changes:
                        st.markdown(f"- ✅ {c}")
                except Exception:
                    st.write(row["change_list"])

# ---------------------------------------------------------
# VIEW 2: DRIFT SCORES ANALYTICS
# ---------------------------------------------------------
elif nav_view == "📊 Drift Score Analytics":
    st.markdown('<div class="main-header">Policy Drift Analytics</div>', unsafe_allow_html=True)
    st.markdown('<div class="sub-header">Weighted drift score distribution and policy divergence metrics</div>', unsafe_allow_html=True)

    df_tickets = fetch_tickets()

    if df_tickets.empty:
        st.info("No tickets available for drift score analytics.")
    else:
        col1, col2 = st.columns([2, 1])

        with col1:
            st.subheader("Drift Score by Regulator & Domain")
            fig = px.bar(
                df_tickets,
                x="domain",
                y="drift_score",
                color="priority",
                hover_data=["ticket_id", "regulator", "affected_policies"],
                title="Policy Drift Score per Domain",
                labels={"drift_score": "Drift Score (0.0 - 1.0)", "domain": "BFSI Domain"},
                color_discrete_map={
                    "HIGH (P1)": "#EF4444",
                    "MEDIUM (P2)": "#F59E0B",
                    "LOW (P3)": "#6366F1",
                    "Archive": "#10B981"
                }
            )
            fig.update_layout(yaxis_range=[0, 1.0])
            st.plotly_chart(fig, use_container_width=True)

        with col2:
            st.subheader("Priority Distribution")
            fig_pie = px.pie(
                df_tickets,
                names="priority",
                title="Priority Breakdown",
                color="priority",
                color_discrete_map={
                    "HIGH (P1)": "#EF4444",
                    "MEDIUM (P2)": "#F59E0B",
                    "LOW (P3)": "#6366F1"
                }
            )
            st.plotly_chart(fig_pie, use_container_width=True)

        st.markdown("---")
        st.subheader("Drift Score Calculation Formula Reference")
        st.latex(r"\text{Drift Score} = 0.60 \times \text{Cosine Sim} + 0.25 \times \text{Keyword Match} + 0.15 \times \text{NER Entity Match}")

# ---------------------------------------------------------
# VIEW 3: RBI AUDIT TRAIL
# ---------------------------------------------------------
elif nav_view == "📜 RBI Audit Trail":
    st.markdown('<div class="main-header">RBI-Inspectable Audit Trail</div>', unsafe_allow_html=True)
    st.markdown('<div class="sub-header">Granular step-by-step decision log of all agent transitions and policy mappings</div>', unsafe_allow_html=True)

    df_audit = fetch_audit_logs()

    if df_audit.empty:
        st.info("No audit logs recorded in SQLite compliance_audit table.")
    else:
        st.dataframe(
            df_audit[["id", "timestamp", "circular_id", "agent_name", "step", "action", "details"]],
            use_container_width=True,
            column_config={
                "id": st.column_config.NumberColumn("Log ID"),
                "timestamp": st.column_config.DatetimeColumn("Timestamp"),
                "agent_name": st.column_config.TextColumn("Agent Node"),
                "details": st.column_config.TextColumn("RBI Audit Details", width="large")
            }
        )

        # Download CSV export for regulatory reporting
        csv = df_audit.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="📥 Download RBI Audit Log (CSV)",
            data=csv,
            file_name="rbi_compliance_audit_trail.csv",
            mime="text/csv"
        )

# ---------------------------------------------------------
# VIEW 4: ASK AI (RAG CHATBOT)
# ---------------------------------------------------------
elif nav_view == "💬 Ask AI (RAG Chatbot)":
    st.markdown('<div class="main-header">💬 Ask AI — Regulatory Assistant</div>', unsafe_allow_html=True)
    st.markdown('<div class="sub-header">Powered by Qwen 2.5 + Hybrid RAG (ChromaDB × BM25) over SEBI circulars and Bank of India policies</div>', unsafe_allow_html=True)
    import requests as _requests

    # ── Custom Chat UI Styles ──
    st.markdown("""
    <style>
        .chat-container { display: flex; flex-direction: column; gap: 12px; margin-bottom: 20px; }
        .user-bubble {
            background: linear-gradient(135deg, #1E3A8A, #2563EB);
            color: white;
            padding: 12px 18px;
            border-radius: 18px 18px 4px 18px;
            max-width: 78%;
            align-self: flex-end;
            margin-left: auto;
            font-size: 0.95rem;
            box-shadow: 0 2px 8px rgba(37,99,235,0.3);
        }
        .bot-bubble {
            background: #F1F5F9;
            color: #1E293B;
            padding: 14px 18px;
            border-radius: 18px 18px 18px 4px;
            max-width: 85%;
            align-self: flex-start;
            font-size: 0.95rem;
            border-left: 4px solid #3B82F6;
            box-shadow: 0 2px 8px rgba(0,0,0,0.06);
            line-height: 1.6;
        }
        .bot-label { font-size: 0.75rem; color: #6B7280; margin-bottom: 4px; font-weight: 600; }
        .user-label { font-size: 0.75rem; color: #93C5FD; margin-bottom: 4px; font-weight: 600; text-align: right; }
        .source-badge {
            display: inline-block;
            background: #EFF6FF;
            color: #1D4ED8;
            border: 1px solid #BFDBFE;
            border-radius: 8px;
            padding: 2px 8px;
            font-size: 0.75rem;
            margin: 2px;
        }
        .chat-input-area {
            position: sticky;
            bottom: 0;
            background: white;
            padding-top: 12px;
            border-top: 1px solid #E2E8F0;
        }
    </style>
    """, unsafe_allow_html=True)

    st.markdown("---")

    # ── Chat History Display ──
    if not st.session_state.get("chat_history"):
        st.info("👋 Hello! I'm your AI Compliance Assistant. Ask me anything about SEBI/RBI regulations, Bank of India policies, KYC norms, reporting timelines, penalties, or any compliance topic.")
    else:
        for chat in st.session_state.chat_history:
            # User bubble
            st.markdown(f"""
            <div class="chat-container">
                <div>
                    <div class="user-label">👤 You</div>
                    <div class="user-bubble">{chat['query']}</div>
                </div>
            </div>
            """, unsafe_allow_html=True)

            # Bot bubble
            st.markdown(f"""
            <div class="chat-container">
                <div>
                    <div class="bot-label">🤖 Compliance AI (Qwen 2.5)</div>
                    <div class="bot-bubble">{chat['answer'].replace(chr(10), '<br>')}</div>
                </div>
            </div>
            """, unsafe_allow_html=True)

            # Sources expander
            if chat.get("sources"):
                with st.expander(f"📚 View {len(chat['sources'])} retrieved source document(s)", expanded=False):
                    for i, s in enumerate(chat["sources"], 1):
                        st.markdown(f"**[{i}] {s.get('doc_name', 'Document')}** — Domain: `{s.get('domain', 'N/A')}` | Similarity: `{s.get('similarity', 0)}`")
                        st.caption(s.get("text", "")[:400] + ("..." if len(s.get("text", "")) > 400 else ""))
                        if i < len(chat["sources"]):
                            st.divider()

            st.markdown("<br>", unsafe_allow_html=True)

    # ── Input Area ──
    st.markdown('<div class="chat-input-area">', unsafe_allow_html=True)
    col_input, col_btn, col_clear = st.columns([7, 1.2, 1.2])

    with col_input:
        user_query = st.text_input(
            label="chat_input",
            label_visibility="collapsed",
            placeholder="💬 Ask me anything — regulations, compliance, finance, or anything else...",
            key="chat_input_box"
        )
    with col_btn:
        send_clicked = st.button("Send 🚀", type="primary", use_container_width=True)
    with col_clear:
        if st.button("Clear 🗑️", use_container_width=True):
            st.session_state.chat_history = []
            st.rerun()
    st.markdown('</div>', unsafe_allow_html=True)

    # ── Handle Send ──
    if (send_clicked or user_query) and user_query and user_query.strip():
        # Prevent duplicate sends
        last_query = st.session_state.chat_history[-1]["query"] if st.session_state.chat_history else ""
        if user_query.strip() != last_query:
            with st.spinner("🔍 Searching regulations & generating answer with Qwen 2.5..."):
                try:
                    # Call the FastAPI backend (which runs the full RAG + LLM pipeline)
                    api_payload = {
                        "query": user_query.strip(),
                        "regulator": "ALL",
                        "chat_history": [
                            {"query": c["query"], "answer": c["answer"]}
                            for c in st.session_state.chat_history[-4:]
                        ]
                    }
                    resp = _requests.post(
                        "http://localhost:8001/api/chat",
                        json=api_payload,
                        timeout=120
                    )

                    if resp.status_code == 200:
                        data = resp.json()
                        answer = data.get("answer", "No response received.")
                        sources = data.get("sources", [])
                    else:
                        answer = f"⚠️ API error (HTTP {resp.status_code}). Please ensure the FastAPI server is running on port 8000."
                        sources = []

                except _requests.exceptions.ConnectionError:
                    # Fallback: call directly via search_similar + LLM if API is down
                    try:
                        from langchain_ollama import OllamaLLM
                        from langchain_core.prompts import PromptTemplate

                        matched = search_similar(query_text=user_query.strip(), top_k=5)
                        context_str = "\n\n".join([
                            f"[{i+1}] {m.get('doc_name','Doc')}: {m.get('text','')}"
                            for i, m in enumerate(matched[:4])
                        ]) if matched else "No documents found."

                        history_str = "\n".join([
                            f"User: {c['query']}\nAssistant: {c['answer']}"
                            for c in st.session_state.chat_history[-3:]
                        ]) or "No previous conversation."

                        prompt = f"""You are a helpful, knowledgeable AI assistant. You are also an expert in Indian banking regulations (SEBI, RBI), compliance, and finance.

Regulatory Context (use only if relevant):
{context_str}

Conversation History:
{history_str}

User: {user_query.strip()}

Instructions:
- Answer the question directly and conversationally.
- If it's a greeting, respond warmly and introduce yourself.
- If it's compliance/regulatory, use the context above and be specific.
- If it's a general question, answer from your knowledge.
- NEVER say "I don't know" or refuse. Always give a useful response.
- Keep answers concise unless asked for detail.

Assistant:"""
                        llm_model = os.getenv("LLM_MODEL", "qwen2.5:14b")
                        ollama_url = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
                        llm = OllamaLLM(model=llm_model, base_url=ollama_url, temperature=0.3)
                        answer = llm.invoke(prompt).strip()
                        sources = matched
                    except Exception as llm_err:
                        answer = f"⚠️ Could not reach the AI backend. Error: {llm_err}"
                        sources = []
                except Exception as e:
                    answer = f"⚠️ Unexpected error: {str(e)}"
                    sources = []

            st.session_state.chat_history.append({
                "query": user_query.strip(),
                "answer": answer,
                "sources": sources
            })
            st.rerun()
