import os
import json
import sqlite3
import pandas as pd
import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
from dotenv import load_dotenv

from db import get_connection, init_db
from embeddings import search_similar, get_chroma_client, embedder
from agents import run_agent_pipeline_on_circular

load_dotenv()

# Page configuration
st.set_page_config(
    page_title="AI Compliance Copilot | Bank of India",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for UI aesthetics
st.markdown("""
<style>
    .main-header {
        font-size: 2.2rem;
        font-weight: 700;
        color: #1E3A8A;
        margin-bottom: 0px;
    }
    .sub-header {
        font-size: 1.0rem;
        color: #4B5563;
        margin-bottom: 20px;
    }
    .metric-card {
        background-color: #F8FAFC;
        border-radius: 10px;
        padding: 15px;
        border-left: 5px solid #3B82F6;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .badge-high {
        background-color: #FEE2E2;
        color: #991B1B;
        padding: 4px 10px;
        border-radius: 12px;
        font-weight: 600;
        font-size: 0.85rem;
    }
    .badge-medium {
        background-color: #FEF3C7;
        color: #92400E;
        padding: 4px 10px;
        border-radius: 12px;
        font-weight: 600;
        font-size: 0.85rem;
    }
    .badge-low {
        background-color: #E0E7FF;
        color: #3730A3;
        padding: 4px 10px;
        border-radius: 12px;
        font-weight: 600;
        font-size: 0.85rem;
    }
</style>
""", unsafe_allow_html=True)

init_db()

# Sidebar Navigation
st.sidebar.image("https://img.icons8.com/color/96/shield-with-signature.png", width=70)
st.sidebar.title("Compliance Copilot")
st.sidebar.caption("Indian BFSI Regulatory Drift System")

nav_view = st.sidebar.radio(
    "Navigation",
    ["🎟️ Compliance Tickets", "📊 Drift Score Analytics", "📜 RBI Audit Trail", "💬 Ask AI (RAG Chatbot)"]
)

st.sidebar.markdown("---")
st.sidebar.subheader("System Status")
st.sidebar.success("● Database: Connected (SQLite)")
st.sidebar.info("● Vector Store: Active (ChromaDB)")
st.sidebar.info("● Ollama LLM: llama3.1:8b")

# Helper Data Functions
def fetch_tickets():
    conn = get_connection()
    df = pd.read_sql_query("SELECT * FROM compliance_tickets ORDER BY created_at DESC", conn)
    conn.close()
    return df

def fetch_audit_logs():
    conn = get_connection()
    df = pd.read_sql_query("SELECT * FROM compliance_audit ORDER BY id DESC", conn)
    conn.close()
    return df

def fetch_queue():
    conn = get_connection()
    df = pd.read_sql_query("SELECT * FROM document_queue ORDER BY id DESC", conn)
    conn.close()
    return df

# ---------------------------------------------------------
# VIEW 1: TICKETS
# ---------------------------------------------------------
if nav_view == "🎟️ Compliance Tickets":
    st.markdown('<div class="main-header">Compliance Tickets</div>', unsafe_allow_html=True)
    st.markdown('<div class="sub-header">Actionable compliance tickets generated by 3-agent LangGraph workflow</div>', unsafe_allow_html=True)

    df_tickets = fetch_tickets()

    if df_tickets.empty:
        st.warning("No compliance tickets found in SQLite database. Run `python run_pipeline.py` to process queued circulars.")
    else:
        # Metrics Top Bar
        col1, col2, col3, col4 = st.columns(4)
        high_count = len(df_tickets[df_tickets["priority"].str.contains("HIGH", na=False)])
        med_count = len(df_tickets[df_tickets["priority"].str.contains("MEDIUM", na=False)])
        low_count = len(df_tickets[df_tickets["priority"].str.contains("LOW", na=False)])

        with col1:
            st.metric("Total Tickets", len(df_tickets))
        with col2:
            st.metric("High Priority (P1)", high_count)
        with col3:
            st.metric("Medium Priority (P2)", med_count)
        with col4:
            st.metric("Low Priority (P3)", low_count)

        st.markdown("---")
        
        # Filter controls
        reg_filter = st.multiselect("Filter by Regulator", options=df_tickets["regulator"].unique(), default=df_tickets["regulator"].unique())
        prio_filter = st.multiselect("Filter by Priority", options=df_tickets["priority"].unique(), default=df_tickets["priority"].unique())

        filtered_df = df_tickets[
            (df_tickets["regulator"].isin(reg_filter)) &
            (df_tickets["priority"].isin(prio_filter))
        ]

        for idx, row in filtered_df.iterrows():
            priority_str = row["priority"]
            badge_class = "badge-high" if "HIGH" in priority_str else ("badge-medium" if "MEDIUM" in priority_str else "badge-low")
            
            with st.expander(f"📌 [{row['ticket_id']}] {row['regulator']} - {row['domain']} (Drift Score: {row['drift_score']:.2f})", expanded=(idx==0)):
                st.markdown(f"**Priority**: <span class='{badge_class}'>{priority_str}</span> | **Regulator**: `{row['regulator']}` | **Domain**: `{row['domain']}` | **Status**: `{row['status']}`", unsafe_allow_html=True)
                st.markdown(f"**Circular ID**: `{row['circular_id']}` | **Created At**: `{row['created_at']}`")
                
                st.markdown("### Executive Summary")
                st.info(row["summary"])

                st.markdown("### Affected Internal Policies")
                try:
                    policies = json.loads(row["affected_policies"])
                    for p in policies:
                        st.markdown(f"- 📄 **{p}**")
                except Exception:
                    st.write(row["affected_policies"])

                st.markdown("### Actionable Change Items")
                try:
                    changes = json.loads(row["change_list"])
                    for c in changes:
                        st.markdown(f"- ✅ {c}")
                except Exception:
                    st.write(row["change_list"])

# ---------------------------------------------------------
# VIEW 2: DRIFT SCORES ANALYTICS
# ---------------------------------------------------------
elif nav_view == "📊 Drift Score Analytics":
    st.markdown('<div class="main-header">Policy Drift Analytics</div>', unsafe_allow_html=True)
    st.markdown('<div class="sub-header">Weighted drift score distribution and policy divergence metrics</div>', unsafe_allow_html=True)

    df_tickets = fetch_tickets()

    if df_tickets.empty:
        st.info("No tickets available for drift score analytics.")
    else:
        col1, col2 = st.columns([2, 1])

        with col1:
            st.subheader("Drift Score by Regulator & Domain")
            fig = px.bar(
                df_tickets,
                x="domain",
                y="drift_score",
                color="priority",
                hover_data=["ticket_id", "regulator", "affected_policies"],
                title="Policy Drift Score per Domain",
                labels={"drift_score": "Drift Score (0.0 - 1.0)", "domain": "BFSI Domain"},
                color_discrete_map={
                    "HIGH (P1)": "#EF4444",
                    "MEDIUM (P2)": "#F59E0B",
                    "LOW (P3)": "#6366F1",
                    "Archive": "#10B981"
                }
            )
            fig.update_layout(yaxis_range=[0, 1.0])
            st.plotly_chart(fig, use_container_width=True)

        with col2:
            st.subheader("Priority Distribution")
            fig_pie = px.pie(
                df_tickets,
                names="priority",
                title="Priority Breakdown",
                color="priority",
                color_discrete_map={
                    "HIGH (P1)": "#EF4444",
                    "MEDIUM (P2)": "#F59E0B",
                    "LOW (P3)": "#6366F1"
                }
            )
            st.plotly_chart(fig_pie, use_container_width=True)

        st.markdown("---")
        st.subheader("Drift Score Calculation Formula Reference")
        st.latex(r"\text{Drift Score} = 0.60 \times \text{Cosine Sim} + 0.25 \times \text{Keyword Match} + 0.15 \times \text{NER Entity Match}")

# ---------------------------------------------------------
# VIEW 3: RBI AUDIT TRAIL
# ---------------------------------------------------------
elif nav_view == "📜 RBI Audit Trail":
    st.markdown('<div class="main-header">RBI-Inspectable Audit Trail</div>', unsafe_allow_html=True)
    st.markdown('<div class="sub-header">Granular step-by-step decision log of all agent transitions and policy mappings</div>', unsafe_allow_html=True)

    df_audit = fetch_audit_logs()

    if df_audit.empty:
        st.info("No audit logs recorded in SQLite compliance_audit table.")
    else:
        st.dataframe(
            df_audit[["id", "timestamp", "circular_id", "agent_name", "step", "action", "details"]],
            use_container_width=True,
            column_config={
                "id": st.column_config.NumberColumn("Log ID"),
                "timestamp": st.column_config.DatetimeColumn("Timestamp"),
                "agent_name": st.column_config.TextColumn("Agent Node"),
                "details": st.column_config.TextColumn("RBI Audit Details", width="large")
            }
        )

        # Download CSV export for regulatory reporting
        csv = df_audit.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="📥 Download RBI Audit Log (CSV)",
            data=csv,
            file_name="rbi_compliance_audit_trail.csv",
            mime="text/csv"
        )

# ---------------------------------------------------------
# VIEW 4: ASK AI (RAG CHATBOT)
# ---------------------------------------------------------
elif nav_view == "💬 Ask AI (RAG Chatbot)":
    st.markdown('<div class="main-header">Ask AI — Regulatory Assistant</div>', unsafe_allow_html=True)
    st.markdown('<div class="sub-header">RAG Chatbot over SEBI circulars and Bank of India policy vector stores</div>', unsafe_allow_html=True)

    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []

    user_query = st.text_input("Ask any question regarding SEBI/RBI circulars or Bank of India policies:", placeholder="e.g. What is the re-KYC frequency required for high risk bank accounts?")

    if st.button("Search & Answer", type="primary") and user_query:
        with st.spinner("Searching ChromaDB collections & generating response..."):
            matched_policies = search_similar(query_text=user_query, top_k=3)
            
            context_str = "\n\n".join([f"Source [{m.get('doc_name')} | Sim: {m.get('similarity')}]: {m.get('text')}" for m in matched_policies])

            # Response synthesis
            answer = f"Based on Bank of India policies and regulatory circulars:\n\n"
            if matched_policies:
                answer += f"**Key Finding**: {matched_policies[0].get('text')}\n\n"
                answer += f"**Relevant Policy Document**: `{matched_policies[0].get('doc_name')}` (Cosine Similarity: {matched_policies[0].get('similarity')})"
            else:
                answer += "No exact matching policy chunk found in vector store."

            st.session_state.chat_history.append({"query": user_query, "answer": answer, "sources": matched_policies})

    for chat in reversed(st.session_state.chat_history):
        st.markdown(f"**👤 User**: {chat['query']}")
        st.markdown(f"**🤖 Copilot**: {chat['answer']}")
        with st.expander("🔍 View Retrieved Vector Store Context"):
            for s in chat.get("sources", []):
                st.caption(f"📄 **{s.get('doc_name')}** (Domain: {s.get('domain')}, Sim: {s.get('similarity')})")
                st.code(s.get("text"))
        st.markdown("---")
